apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations: 
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  tls:
  - hosts: 
    - {{ .Values.app.url.course_root }}
    secretName: tls-{{ .Release.Name }}-service-ingress-http
  rules:
    - host: {{ .Values.app.url.course_root }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-ctsserver-service
              port:
                name: cts-web-port