---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ctsserver-{{ .Release.Name }}
  name: {{ .Release.Name }}-ctsserver-service
spec:
  ports:
    - name: cts-web-port
      port: 80
      protocol: TCP
      targetPort: cts-web-port
  selector:
    app: ctsserver-{{ .Release.Name }}