replicaCount: 1

image:
  name: nginx
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

registry:
  regcred:
    enabled: false
  url: 

namespace: default 

app:
  url:
    cts_root: cts.mydomain.com

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  className: ""
