name: CI - Build the server on every commit

on: 
  push:
    # only trigger on branches, not on tags
    branches: '**'

env:
  IMAGE_NAME: cts_server
  CONTAINER_NAME: ctsservertest
  TEST_URL: http://localhost:8000/ping

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Build the contianer
      run : docker build -t "$IMAGE_NAME" . --no-cache
      working-directory: ./cts_server
    
    - name: Run the contianer in the background
      run : docker run -d --name -p 8000:8000 "$CONTAINER_NAME" "$IMAGE_NAME"
      working-directory: ./cts_server
    
    - name: Perform tests on the server
      run: |
        RESPONSE=$(curl -s "$TEST_URL")
        HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$TEST_URL")

        # evaluate the result
        if [ "$HTTP_CODE" -eq 200 ] && echo "$RESPONSE" | grep -q "OK"; then
            echo "Test passed: Status code is 200 and response body is correct"
        else
            echo "Test failed"
            echo "Status code: $HTTP_CODE"
            echo "Response body: $RESPONSE"
            exit 1
        fi

    - name: Cleanup the container and continaer image
      if: always()
      run: |
        docker stop "$CONTAINER_NAME" || true
        docker rm "$CONTAINER_NAME" || true
        docker rmi "$IMAGE_NAME" || true