name: CD - Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

env:
  IMAGE_NAME: cts_server
  DEPLOYMENT_NAME: ctsserver
  REGISTRY_URL: myregistry.io
  NAMESPACE: fun7

jobs:
  build-and-deploy:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Build the contianer
      run : | 
        echo "Building container..."
        docker build -t "$REGISTRY_URL:$IMAGE_NAME" . --no-cache
        # docker push "$REGISTRY_URL:$IMAGE_NAME"
      working-directory: ./cts_server

    - name: Deploy the application
      run : |
        echo "Update deployment using Helm ..."
        # force resource updates through a replacement strategy
        # helm update --install --force -n  "$NAMESPACE" --create-namespace ctsserver . 
      working-directory: ./helmchart/CTS
      
    - name: Cleanup the container and continaer image
      if: always()
      run: |
        docker rmi "$REGISTRY_URL:$IMAGE_NAME" || true